http:  
  port:"![7lfNJW6/zOc=]"
database:
  uhub:    
    host: "![sn0/bkKC48z/NTUjMAQSqg==]"
    port: "![IYFYwfs4WCI=]" 
    user: "![jvQys9l5oL8=]"
    password: "![etPTVsrVXF9Og1fIG36Dvg==]"   
    instance: "![JnfuSpVw020=]"